/****************************************************************************
 * This is free and unencumbered software released into the public domain.
 *
 * Anyone is free to copy, modify, publish, use, compile, sell, or
 * distribute this software, either in source code form or as a compiled
 * binary, for any purpose, commercial or non-commercial, and by any
 * means.
 *
 * In jurisdictions that recognize copyright laws, the author or authors
 * of this software dedicate any and all copyright interest in the
 * software to the public domain. We make this dedication for the benefit
 * of the public at large and to the detriment of our heirs and
 * successors. We intend this dedication to be an overt act of
 * relinquishment in perpetuity of all present and future rights to this
 * software under copyright law.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 *
 * For more information, please refer to <https://unlicense.org>
 ***************************************************************************/
 /*--------------------------------------------------------------------------
    HALKEN vpk0 Tool ( Work in Progress ) v0.75

    Author  : White Guy That Don't Smile
    Date    : 2022/04/25, Monday, April 25th; 2042 HOURS
    License : UnLicense | Public Domain

    This is a data compression tool presented with the goal of
    *faithfully reverse-engineering the compression aspect of
    HAL Laboratory's enigmatic algorithm.
    It supports decompression by using the code found within
    one of their Nintendo 64 titles, Pokémon Snap.

    As of present, the compression portion is at 50% with the LZ
    routine being faithfully deduced (I hope).

    The exact Huffman routine has yet to be unraveled, therefore,
    this tool temporarily uses bit-stream LZ encoding.

    *This project yields inspiration from CaitSith2 in a number
    of ways, however, the key motive for this project is to
    replicate the format, _faithfully_ (i.e. 1:1 encoded data).
---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------
    HALKEN LZ Routine v1.00

    Author  : White Guy That Don't Smile
    Date    : 2022/04/25, Monday, April 25th; 2042 HOURS
    License : UnLicense | Public Domain

    This is a Lempel-Ziv compression routine siphoned from the
    AGB SDK tool "agbcomp" - modified to comply with the parameters
    recorded from decoded sample data generated by HAL Laboratory.

    ####  Confirmed LZ Parameters  ####

    Minimum Offset : 0x0001 , Minimum Length : 0x03
    Maximum Offset : 0xFFFF , Maximum Length : 0xFF

    0 Flag : Process 8 bits, verbatim.
    1 Flag : Process Length-Displacement information.

    ####  Supplementary Hypothetical Parameters  ####

    < IF >
        the next reference address, is uneven
        | OR |
        the initial match offset, plus two,
        is not-equal to
        the lookahead match offset
        | OR |
        the lookahead match length minus the initial match length,
        is less-than or equal-to
        three
    < THEN >
        go to the end of the loop
---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------
    ####  LZ Audits  ####

    <  Nintendo 64  >

        [N64] : Kirby 64: The Crystal Shards
        [???? / ????] : To do....

        [N64] : Pokémon Snap
        [EUR][0003 / 0003] : Success
        [JAP][0003 / 0003] : Success
        [USA][0003 / 0003] : Success

        [N64] : Shigesato Itoi's No. 1 Bass Fishing - Definitive Edition!
        [JAP][0001 / 0001] : Success

        [N64] : Super Smash Bros.
        [EUR][0516 / 0516] : Success
        [JAP][0474 / 0474] : Success
        [USA][0498 / 0498] : Success

    <  Game Boy Advance  >

        [AGB] : e-Reader ROM
        [JAP][0003 / 0003] : Success
        [JAP][0004 / 0004] : Success [e-Reader+]
        [USA][0003 / 0003] : Success

        [AGB] : Pokémon Emerald Version
        [0001 / 0001] : Success

        [AGB] : Pokémon FireRed Version
        [0001 / 0001] : Success

        [AGB] : Pokémon LeafGreen Version
        [0001 / 0001] : Success

        [AGB] : Super Mario Advance 4 - Super Mario Bros. 3
        [0001 / 0001] : Success
---------------------------------------------------------------------------*/
#include "vpk0.h"
#include <stdio.h>
#include <stdlib.h>



static void _search( u8 *src,
                     const u32  srcpos, const u32  srclen,
                           u32 *match_offset, u32 *match_length )
{
  u8 *head;
  u8 *tail;
  u32 offset;
  u32 length;
  u32 window;
  int nominal;

  *match_offset = 0;
  *match_length = 0;
  offset   = 1;
  window   = (srcpos < 0x10000) ? 1 : srcpos - 0xFFFF;
  nominal  = ((srcpos < srclen) << 2) | 2;
  nominal |= window <= srcpos;

  while ( nominal == 7 )
  {
    nominal = 4;
    tail    = &src[((i32)srcpos - offset)];

    if ( *tail == src[srcpos] )
    {
      length = 1;
      head = &src[srcpos];

      while ( (*++head == *++tail) && (++length < 0xFF) );

      if ( srclen <= (srcpos + length) ) length = srclen - srcpos;

      if ( (2 < length) && (*match_length < length) )
      {
        *match_offset = offset;
        *match_length = length;
      }
    }

    nominal |= ((++offset < 0x10000U) << 1);
    nominal |= ++window <= srcpos;
  }

  return;
}



static void _null_block( u8 *def )
{
  if ( def != (u8 *)0 )
  {
    free( def );
    def = (u8 *)0;
  }

  return;
}



static u8 *_produce_lz( u8 *src, u8 **dst, const u32 srclen, u32 **dstlen )
{
  u8  *def;
  u32  dp;
  u32  cp;
  u32  match_offset;
  u32  match_length;
  u32  lookahead_offset;
  u32  lookahead_length;
  u32  mask;
  register u32 srcpos;
  u32  ndp;
  u32  i;
  u8   cmds;
  u8   bytes[3];
  int  nominal;

  cp  = 0;
  dp  = cp + 1U;
  ndp = 0x1000U << ENC_GREED;
  def = malloc( (ndp << 2U) );
  srcpos = 0;
  cmds   = 0;
  mask   = 0x80U;

#define extend_buffer \
  if ( ndp == dp ) \
  { \
    ndp += ((0x1000U << 2) << ENC_GREED); \
\
    if ( (def = realloc( def, ndp )) == (u8 *)0 ) goto err; \
  }

#define shift_mask \
  if ( (mask >>= 1) == 0 ) \
  { \
    mask = 0x80U; \
    def[cp] = cmds; \
    cp = dp++; \
\
    if ( ndp == dp ) \
    { \
      ndp += ((0x1000U << 2) << ENC_GREED); \
\
      if ( (def = realloc( def, ndp )) == (u8 *)0 ) goto err; \
    } \
\
    cmds = 0; \
  }

  while ( srcpos < srclen )
  {
    _search( src, srcpos, srclen, &match_offset, &match_length );

    if ( match_length < 3U )
    {
      def[dp++] = src[srcpos++];
      extend_buffer;
    }
    else
    {
      _search( src, (srcpos + 1U), srclen,
               &lookahead_offset, &lookahead_length );

      if ( (match_length + 1U) <= lookahead_length )
      {
        nominal   = 0;
        def[dp++] = src[srcpos++];
        extend_buffer;
        shift_mask;
        /*---------------------------------------------
        Testing against these conditions seems to fall
        in line with the method needed to reproduce the
        LZ data siphoned from preexisting "vpk0" data.
        ---------------------------------------------*/
        nominal |= (srcpos & 1);
        nominal |= (match_offset + 2U) != lookahead_offset;
        nominal |= (lookahead_length - match_length) <= 3;

        if ( nominal != 0 ) continue;
        else
        {
          match_offset = lookahead_offset;
          match_length = lookahead_length;
        }
      }

      cmds |= mask;
      bytes[0] = (u8)match_offset;
      bytes[1] = (u8)(match_offset >> 8);
      bytes[2] = (u8)match_length;
      i = 0;

      while ( i < 3U )
      {
        def[dp++] = bytes[i++];
        extend_buffer;
      }

      srcpos += match_length;
    }

    shift_mask;
  }

  if ( mask != 0x80U ) def[cp] = cmds;
  else --dp;

  **dstlen = (u32)dp;

  if ( (*dst = (u8 *)calloc( **dstlen, sizeof(u8) )) == (u8 *)0 ) goto err;

  for ( srcpos = 0; srcpos < dp; *(*dst + srcpos) = def[srcpos], srcpos++ );

  _null_block( def );
  return *dst;

err:

  printf("RAM Unavailable!\n");

  if ( *dst != (u8 *)0 ) free( *dst );

  _null_block( def );
  return *dst = (u8 *)0;
}



u8 *_lz( u8 *src, u8 **dst, const u32 srclen, u32 *dstlen )
{
  return *dst = _produce_lz( src, &*dst, srclen, &dstlen );
}
